services:
  web:
    build: ./apache
    container_name: itop-web
    volumes:
      - ./web:/var/www/html
      - ./sessions:/var/lib/php/sessions
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - itop-net

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    container_name: itop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ["--disable-log-bin"]
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - itop-net

volumes:
  dbdata:

networks:
  itop-net:
